name: Node CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        node-version: [22.x, 24.x, 26.x]
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: ./.github/actions/configure-nodejs
        with:
          node-version: ${{ matrix.node-version }}

      - name: Lint
        run: npm run lint

      - name: Check Formatting with Prettier
        run: npm run prettier

      - name: Build TypeScript
        run: npm run build

      - name: Unit Tests
        run: npm run test

      - name: XML Lint Test
        run: npm run test:xmllint
